-- 初始化数据库表结构
-- 请在 Supabase 控制台的 SQL Editor 中执行此脚本

-- 1. 创建订单表 (orders)
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL,
  product_size TEXT NOT NULL,
  product_category TEXT DEFAULT '',
  product_model TEXT DEFAULT '',
  product_specs TEXT DEFAULT '',
  quantity INTEGER DEFAULT 1,
  transaction_time TEXT DEFAULT '',
  order_notes TEXT DEFAULT '',
  mark TEXT DEFAULT 'pending_design',
  export_status TEXT DEFAULT 'not_exported',
  exported_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 创建模板表 (templates)
CREATE TABLE IF NOT EXISTS templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image_path TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 创建设计表 (designs)
CREATE TABLE IF NOT EXISTS designs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  canvas_data TEXT,
  preview_path TEXT,
  width INTEGER DEFAULT 800,
  height INTEGER DEFAULT 600,
  background_type TEXT DEFAULT 'white',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 创建分类表 (categories)
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  description TEXT,
  is_default BOOLEAN DEFAULT FALSE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. 插入默认分类数据
INSERT INTO categories (name, display_name, description, is_default, sort_order)
VALUES 
  ('default', '默认', '默认分类', TRUE, 1),
  ('pattern', '图案', '图案类模板', TRUE, 2),
  ('text', '文字', '文字类模板', TRUE, 3),
  ('shape', '形状', '形状类模板', TRUE, 4)
ON CONFLICT (name) DO NOTHING;

-- 6. 启用 RLS (虽然目前后端使用 Service Key 绕过，但为了安全建议开启)
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE designs ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- 7. 创建简单的全权访问策略 (因为主要通过后端访问)
-- 注意：如果您后续要开放前端直连，请修改这些策略
CREATE POLICY "Enable all access for service role" ON orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for service role" ON templates FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for service role" ON designs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for service role" ON categories FOR ALL USING (true) WITH CHECK (true);

-- 8. 创建索引以优化查询
CREATE INDEX IF NOT EXISTS idx_orders_mark ON orders(mark);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_designs_order_id ON designs(order_id);
